server:
  port: 8080

nlp:
  base-url: ${NLP_BASE_URL:http://localhost:8000}

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true

management:
  endpoints:
    web.exposure.include: health,info
  endpoint:
    health.probes.enabled: true
